version: '2'

services:

  transmission:
    image: cdrage/transmission
    volumes:
      - ./media:/var/lib/transmission-daemon/downloads
    ports:
      - "9091:9091"
    environment:
      - TRUSER=admin
      - TRPASSWD=admin
    restart: always

  jackett:
    image: linuxserver/jackett
    volumes:
      - ./config/jackett:/config
      - /dev/rtc:/dev/rtc:ro
    ports:
      - "9117:9117"
    restart: always

  sonarr:
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - ./config/sonarr:/config
      - /dev/rtc:/dev/rtc:ro
    depends_on:
      - transmission
    restart: always
  
  radarr:
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - /dev/rtc:/dev/rtc:ro
    depends_on:
      - transmission
    restart: always

  plex:
    image: wernight/plex-media-server
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for controlling Plex for Roku via Plex Companion
      - "8324:8324"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ./config/plex:/config
      - ./media:/media
    environment:
      - X_PLEX_TOKEN=KEYHERE
    network_mode: host
    restart: always
