apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: couchpotato
  name: couchpotato
spec:
  ports:
  - name: "5050"
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    service: couchpotato
status:
  loadBalancer: {}
