apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: plex
  name: plex
spec:
  ports:
  - name: "32400"
    port: 32400
    protocol: TCP
    targetPort: 32400
  - name: "1900"
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: "32469"
    port: 32469
    protocol: TCP
    targetPort: 32469
  - name: "3005"
    port: 3005
    protocol: TCP
    targetPort: 3005
  - name: "5353"
    port: 5353
    protocol: UDP
    targetPort: 5353
  - name: "8324"
    port: 8324
    protocol: TCP
    targetPort: 8324
  - name: "32410"
    port: 32410
    protocol: UDP
    targetPort: 32410
  - name: "32412"
    port: 32412
    protocol: UDP
    targetPort: 32412
  - name: "32413"
    port: 32413
    protocol: UDP
    targetPort: 32413
  - name: "32414"
    port: 32414
    protocol: UDP
    targetPort: 32414
  selector:
    service: plex
status:
  loadBalancer: {}
