apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: transmission
  name: transmission
spec:
  ports:
  - name: "9091"
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    service: transmission
status:
  loadBalancer: {}
